---
- apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome'

- apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Update repositories cache and install google-chrome
  apt:
    name: google-chrome-stable
    update_cache: yes
