---
# Automatic ansible script based on on
# https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
# without ruby

- name: Install packages required for downloading/building Vim
  apt:
    name: "{{ item }}"
  with_items: [libncurses5-dev, libgnome2-dev, libgnomeui-dev, libgtk2.0-dev, libatk1.0-dev, libbonoboui2-dev, libcairo2-dev, libx11-dev, libxpm-dev, libxt-dev, python-dev, python3-dev, lua5.3, liblua5.3-dev, libperl-dev, git, checkinstall]

- name: Get Vim source
  git:
    repo: 'https://github.com/vim/vim.git'
    dest: /srv/vim

- name: Configure Vim build (without ruby)
  command:
    ./configure --with-features=huge
            --enable-multibyte
            --with-python-config-dir=/usr/lib/python2.7/config
            --enable-python3interp=yes
            --with-python3-config-dir=/usr/lib/python3.5/config
            --enable-perlinterp=yes
            --enable-luainterp=yes
            --enable-gui=gtk2 --enable-cscope --prefix=/usr
  args:
    chdir: /srv/vim

- name: Make Vim
  command: make VIMRUNTIMEDIR=/usr/share/vim/vim80
  args:
    chdir: /srv/vim

- name: Remove any pre-existing Vim packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: [vim, vim-runtime, gvim, vim-tiny, vim-common, vim-gui-common, vim-nox]

- name: Use checkinstall to install Vim
  command: checkinstall -y
  args:
    chdir: /srv/vim

- name: Set vim as alternative to vi
  alternatives:
    name: vi
    link: /usr/bin/vi
    path: /usr/bin/vim

- name: Set vim as alternative for editor
  alternatives:
    name: editor
    link: /usr/bin/editor
    path: /usr/bin/vim
